// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	message "douyin/kitex_gen/message"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetMassageChat(ctx context.Context, req *message.MessageChatReq, callOptions ...callopt.Option) (r *message.MessageChatResp, err error)
	MassageAction(ctx context.Context, req *message.MassageActionReq, callOptions ...callopt.Option) (r *message.MassageActionResp, err error)
	GetLatestMessage(ctx context.Context, req *message.GetLatestMessageReq, callOptions ...callopt.Option) (r *message.GetLatestMessageResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) GetMassageChat(ctx context.Context, req *message.MessageChatReq, callOptions ...callopt.Option) (r *message.MessageChatResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMassageChat(ctx, req)
}

func (p *kMessageServiceClient) MassageAction(ctx context.Context, req *message.MassageActionReq, callOptions ...callopt.Option) (r *message.MassageActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MassageAction(ctx, req)
}

func (p *kMessageServiceClient) GetLatestMessage(ctx context.Context, req *message.GetLatestMessageReq, callOptions ...callopt.Option) (r *message.GetLatestMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLatestMessage(ctx, req)
}
