// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	message "douyin/kitex_gen/message"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return messageServiceServiceInfo
}

var messageServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "messageService"
	handlerType := (*message.MessageService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetMessageChat": kitex.NewMethodInfo(GetMessageChatHandler, newMessageServiceGetMessageChatArgs, newMessageServiceGetMessageChatResult, false),
		"messageAction":  kitex.NewMethodInfo(messageActionHandler, newMessageServiceMessageActionArgs, newMessageServiceMessageActionResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "message",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func GetMessageChatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceGetMessageChatArgs)
	realResult := result.(*message.MessageServiceGetMessageChatResult)
	success, err := handler.(message.MessageService).GetMessageChat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceGetMessageChatArgs() interface{} {
	return message.NewMessageServiceGetMessageChatArgs()
}

func newMessageServiceGetMessageChatResult() interface{} {
	return message.NewMessageServiceGetMessageChatResult()
}

func messageActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*message.MessageServiceMessageActionArgs)
	realResult := result.(*message.MessageServiceMessageActionResult)
	success, err := handler.(message.MessageService).MessageAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newMessageServiceMessageActionArgs() interface{} {
	return message.NewMessageServiceMessageActionArgs()
}

func newMessageServiceMessageActionResult() interface{} {
	return message.NewMessageServiceMessageActionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetMessageChat(ctx context.Context, req *message.MessageChatReq) (r *message.MessageChatResp, err error) {
	var _args message.MessageServiceGetMessageChatArgs
	_args.Req = req
	var _result message.MessageServiceGetMessageChatResult
	if err = p.c.Call(ctx, "GetMessageChat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MessageAction(ctx context.Context, req *message.MessageActionReq) (r *message.MessageActionResp, err error) {
	var _args message.MessageServiceMessageActionArgs
	_args.Req = req
	var _result message.MessageServiceMessageActionResult
	if err = p.c.Call(ctx, "messageAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
