// Code generated by hertz generator.

package main

import (
	"douyin/cmd/api/biz/rpc"
	"douyin/pkg/constants"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	rpc.Init()
	h := server.Default(server.WithHostPorts(constants.ApiServiceWithHostPorts))
	register(h)
	h.Spin()
}
