// Code generated by Kitex v0.3.2. DO NOT EDIT.

package commentservice

import (
	"context"
	"douyin/kitex_gen/comment"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CommentAction(ctx context.Context, req *comment.CommentActionReq, callOptions ...callopt.Option) (r *comment.CommentActionResp, err error)
	MCountComment(ctx context.Context, req *comment.MCountCommentReq, callOptions ...callopt.Option) (r *comment.MCountCommentResp, err error)
	MGetComment(ctx context.Context, req *comment.MGetCommentReq, callOptions ...callopt.Option) (r *comment.MGetCommentResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) CommentAction(ctx context.Context, req *comment.CommentActionReq, callOptions ...callopt.Option) (r *comment.CommentActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, req)
}

func (p *kCommentServiceClient) MCountComment(ctx context.Context, req *comment.MCountCommentReq, callOptions ...callopt.Option) (r *comment.MCountCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MCountComment(ctx, req)
}

func (p *kCommentServiceClient) MGetComment(ctx context.Context, req *comment.MGetCommentReq, callOptions ...callopt.Option) (r *comment.MGetCommentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetComment(ctx, req)
}
